### ISSUE TITLE
Proper categories

### ISSUE THREAD

**Issue by WarttHog** [StoneAgeFactorio/StoneAgeFactorio#10]
I got stuck when I should have been crafting the stone axe because I got used to finding everything from the new mod on the "Intermediate products" tab of the crafting menu.

Would it make sense to move the wooden pipe to the "Logistics" category, and move the buildings which can be placed and the tools to the "Production" category?

**Comment by RomkeVdMeulen** [comment]
Interesting, I hadn't thought of that. I think I'd rather put everything together in the intermediates though: once you graduate the stone age, you'll likely never need these recipes again, so spreading them through the production and logistics tabs will likely just be annoying.

**Comment by WarttHog** [comment]
Agreed.  I've always thought that it would be nice to have some way to forget old techs in Factorio.  Anyway, thought I'd mention it at least.
