### ISSUE TITLE
Support expensive recipes

### ISSUE THREAD

**Issue by WarttHog** [StoneAgeFactorio/StoneAgeFactorio#13]
Maybe not needed for 1.0.0, but at some point it would be nice to support recipe multipliers.  When you see the primitive technology guy build a furnace on YouTube, he has to collect a *ton* of clay and dirt to make it work!  It must give him such satisfaction!  Some players (like me!) may feel the same way.

**Comment by RomkeVdMeulen** [comment]
I already have expensive recipe mode on my to-do list. I'll look into recipe multipliers, see what's needed to support that. It's tied to #11 as well, so need to consider that.

**Comment by RomkeVdMeulen** [comment]
Ah, it's actually technology multiplier, and it only applies to research. But expensive recipes is something the mod can support. I'll have to tweak the resource autoplace settings as well, to make sure there's always enough sand and clay to complete even the expensive recipes.

As for how the exensive recipes should look: I'm thinking increase the number of raw items, increase the probabilities of stuf breaking when sharpening sticks / stones, but don't increase the use of intermediates like e.g. clay grate too much.

**Comment by RomkeVdMeulen** [comment]
I've implemented expensive recipe support. It makes the playthrough a lot more grindy, but I've tried to limit it to somewhat reasonable levels. It may require some more tweaking though.

You can try it out by downloading the [bleeding edge version](https://github.com/StoneAgeFactorio/StoneAgeFactorio/archive/master.zip).
