### ISSUE TITLE
Idea: Using a workstation

### ISSUE THREAD

**Issue by WarttHog** [StoneAgeFactorio/StoneAgeFactorio#15]
In my mind the biggest thing your mod adds to the game is that it extends the phase before automation is possible.  Things should feel very limited and manual, which should make the vanilla counterparts more rewarding once you can finally build them.

In that train of thought, would it be possible to hack the repair tool to make it possible for the player to "use" a tool on a placeable entity?

Imagine this:  You create Crude Copper by creating a worktable or anvil or something.  Then you put the Copper Bloom on (more like in) the table and it reduces the worktable's health to 1hp.  Then you take your hammer and left-click the worktable and as it's healed it makes progress on the copper.  Is that possible?

If so, here are some other ideas that might fit your mod:
- The kiln requires the player to use Bellows on it.
- A new Grinder placeable can turn stone into sand, when the player uses a Crank on it.
- The Wooden Pump also requires a pump for it to fill up the pipes.
- Totally weird but maybe cool idea:  Have a "Thinking Hut" (Gosh that sounds stupid) that you work on with a "Plan" to do Stone Age research.  Research has the benefit of hiding distractions from the user until they're ready for them.  Having to plan out a few stages of the Stone Age and then finally the iron age may have some merit, and this "using" idea would allow you to have research without electricity.

**Comment by RomkeVdMeulen** [comment]
I think I remember reading somewhere that someone had built a "hand-cranked generator" mod, where you had to use rotate to create power. I'll see if I can find it, and whether that mechanic could work here. Your hacked repair tool idea sounds promising as well, I will look into that.

I agree it would be awesome if we can make this work, and would make the gameplay even more distinctive.

I'm not sure about adding research: I kind of like that the mod makes you work even without that, and sets it apart from the later stages. But if it can be made to work well, that might add enough value to override those concerns. Let's revisit that idea once the hand-cranking mechanic is in place.

**Comment by WarttHog** [comment]
> I agree it would be awesome if we can make this work, and would make the gameplay even more distinctive.

I totally agree.  Even if the repair tool sort of works, this might be worth discussing with the devs.  I'm sure many mods would love the ability to "use a thing on another thing".

> Let's revisit [stone age research] once the hand-cranking mechanic is in place.

Totally agree.  The mod's aesthetic might shift depending on how some of these other ideas pan out.

Also thank you so much for being so open to new ideas!  :)

**Comment by RomkeVdMeulen** [comment]
That's why I asked people to test it. All the content so far is only what I could come up with by myself in an afternoon of planning, so I hoped there might be good ideas out there. So thanks, for contributing!

**Comment by RomkeVdMeulen** [comment]
I've built an anvil that needs to be used to make crude copper from a copper bloom, rather than being able to do it by hand. Try it out and let me know what you think: you can download the new version [here](https://www.dropbox.com/s/e6h7hizblcb68vi/StoneAge_0.0.1.zip?dl=1)

**Comment by RomkeVdMeulen** [comment]
Next up, I want to take another look at the mixing pit. I don't like that you have to "craft" a pit with a shovel as an ingredient. I tried making a [version of the mod]() where the pit can be made by placing the shovel on the ground, but early feedback indicates player's don't discover the way to do that and / or can't make it work. I'm thinking perhaps a message displayed when you craft your first shovel that explains the mechanic might help.

**Comment by vaendryl** [comment]
you could have something like

    crude workstation 
      ⤷craft a makeshift anvil from obsidian or something 
      ⤷create some clay for crude self-baking smelter

      crude sawblade made from combining the makeshift anvil and very crude metal
           ⤷crude sawmill (turn wood into  poor quality lumber)
               ⤷build quarry/mine with lumber 
                   ⤷make a proper smelter with proper stone
                        ⤷smelt higher quality ore and make a proper anvil
                              ⤷craft a proper sawblade and build advanced lumber mill
                                    ⤷craft whatever with quality lumber and proper smithy

**Comment by RomkeVdMeulen** [comment]
I'm pretty happy with the manual mechanic of hammering in the latest release. Perhaps the same mechanic can be used in far more places, but I don't think we should overuse it: it's a fun gimmick but can quickly get annoying.
