### ISSUE TITLE
Idea: Shaft-driven buildings

### ISSUE THREAD

**Issue by WarttHog** [StoneAgeFactorio/StoneAgeFactorio#16]
Honestly, this probably needs to be a whole other mod but I thought I'd mention it here because it's related.

It would be awesome to see something like [RotaryCraft](http://rotarycraft.wikia.com/wiki/RotaryCraft_Wiki) in Factorio.  During the Industrial Revolution, factories often used [line shafts](https://en.wikipedia.org/wiki/Line_shaft) to transfer power from a huge, closed-loop steam engine to all the factory workstations.

Not sure if it's possible, but it'd be really cool to build wooden shafts to transfer torque from some power source to various building.  If https://github.com/StoneAgeFactorio/StoneAgeFactorio/issues/15 is possible, then the power source could be the player!

Continuing our trek beyond the bounds of this mod, here's another idea that builds on this, but unfortunately does modify a vanilla entity.  Again looking back at the Industrial Age in history, steam engines were extremely important but they it was a long time before their main use was to generate electricity.  It would be a smoother progression if we made the steam engine output rotary power.  It could then replace the poor player cranking the line shaft to make the factory go, which would feel very rewarding!  Before too long you'll want to electrify your base, so there would be another building named a "Dynamo" which would take rotary power in and give electricity out.

I feel like this idea has potential for a super cool and probably quite big mod, but I'll understand if you just want to close this issue as "out of scope".  Heh.  Thanks for reading anyway!

**Comment by RomkeVdMeulen** [comment]
The idea for crankshaft, driven by steam or water-wheels, came up a number of times while I was exploring this mod. I like the idea, but as you said, it wouldn't fit the constriants for this mod: for stone age I was going for something that didn't work with automation or putting down infrastructure that would later have to be replaced.

However, I don't rule out working on a "Steam Age" mod at some point in the future. It could work together with Stone Age, e.g. like you said by powering jobs the player had to do manually up till then, and transition smoothly into the electrical age (in effect replacing the current burner stage entirely). If I do decide to make that mod, I'll be sure to include you in the design process 😉

**Comment by WarttHog** [comment]
Love it.  I came to the right dude.  :)
