### ISSUE TITLE
Deconstruction planner is broken

### ISSUE THREAD

**Issue by DJMcMayhem** [StoneAgeFactorio/StoneAgeFactorio#7]
> There are sand and clay patches around your spawning point that you'll need. Having trouble finding them? A deconstruction planner might help.

The deconstruction planner won't highlight sand or clay patches. I suspect it might be related to which tool you have equipped.

**Comment by RomkeVdMeulen** [comment]
Exactly. The deconstruction planner will only highlight sand and clay patches if you have a tool equiped that will let you mine them. If not, the patches are marked as non-minable and ignored by the deconstruction planner.

I'll update the tips section to make that clearer.
