### ISSUE TITLE
"Expected Items" shows wrong number.

### ISSUE THREAD

**Issue by DJMcMayhem** [StoneAgeFactorio/StoneAgeFactorio#8]
The number of items I get is dependent on what tool I have equipped, but the "Expected Items" only shows you what you would get if you mined something with an iron pickaxe.

**Comment by RomkeVdMeulen** [comment]
Unfortunately, it doesn't look like the API supports changing the "Expected Items". They are part of the prototype data, which can't be changed on the fly once the game has started.

**Comment by RomkeVdMeulen** [comment]
Although, items do have a prototype property. I'll try messing with it, see if I can't make it work.

**Comment by RomkeVdMeulen** [comment]
Hmm, the EntityPrototype [only has read-only properties](https://lua-api.factorio.com/latest/LuaEntityPrototype.html). No way to override that run-time. So as far as I can tell there's no way to change "Expected items" once the game has begun.
